name: Check
on:
  push:
  pull_request:
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt --check
      - run: cargo test --locked -- --test-threads=1
      - run: cargo clippy --locked --all-targets -- -D warnings
      - run: cargo build --release --locked
